/* jquery-rotator-0.1-min.js
 * 18-02-2012
 * Author: Filip Migdalski (www.migdalski.net)
 *
 * This plugin is Open Source Software released under GPL v3
 *
 * This software comes with no guarantees. Use at your own risk.
 */
 
(function(a){function f(b){var c=0;var d;if(a.browser.msie){c=a(b).css("-ms-transform")}else if(a.browser.webkit){c=a(b).css("-webkit-transform")}else if(a.browser.opera){c=a(b).css("-o-transform")}else if(a.browser.mozilla){c=a(b).css("-moz-transform")}else{c=a(b).css("transform")}if(!c||c=="none"){d=0}else{if(c.indexOf("atrix(")>-1){temp2=c.substring(c.indexOf("atrix(")+6,c.indexOf(")"));matrixx=temp2.split(",");var e=Math.acos(parseFloat(matrixx[0]))*360/(Math.PI*2);var f=Math.asin(parseFloat(matrixx[1]))*360/(Math.PI*2);if(matrixx[0]>0&&matrixx[1]<=0)if(f<0)d=f+360;else d=e;if(matrixx[0]>0&&matrixx[1]>0)d=e;if(matrixx[0]<=0&&matrixx[1]>0)d=e;if(matrixx[0]<=0&&matrixx[1]<=0)d=Math.abs(f)+180}else{d=parseInt(c.substring(c.indexOf("rotate(")+7,c.indexOf("deg")))}}return d}function e(a,c){if(b.value=="absolute"){a=a-c;switch(b.direction){case"short":if(Math.abs(a)>180)a=360+a;break;case"long":if(Math.abs(a)<180)a=360+a;break;case"right":if(c>a)a=360+a;break;case"left":if(c<a)a=a-360;break}}return a}var b;var c=[];var d=0;a.fn.rotate=function(g,h){this.each(function(){b=a.extend({},a.fn.rotate.defaults,h);var j=f(this);var k=this;var l=j;l1=0;t1=0;i=1;g=e(g,j);var m=g/(b.speed/40);width=a(k).width();height=a(k).height();marginl=parseInt(a(k).css("margin-left"));margint=parseInt(a(k).css("margin-top"));if(Math.abs(m)>0){d=0;clearInterval(c);c=setInterval(function(){if(d++>=g/m){clearInterval(c);b.after.call()}else{l+=m;/ * radius correction */;if(++i>=g/m)l=j+g;rad=l*Math.PI*2/360;cosine=Math.round(Math.cos(rad)*1e4)/1e4;sine=Math.round(Math.sin(rad)*1e4)/1e4;mtrx="matrix("+cosine+","+sine+","+ -sine+","+cosine+","+l1+","+t1+")";if(a.browser.msie){if(parseInt(a.browser.version)>=9){a(k).css("-ms-transform",mtrx)}else{ieTransform="progid:DXImageTransform.Microsoft.Matrix(M11="+cosine+", M12="+ -sine+", M21="+sine+", M22="+cosine+", sizingMethod='auto expand')";a(k).css("filter",ieTransform);marginleft=a(k).position().left+(width-a(k).width())/2;margintop=a(k).position().top+(height-a(k).height())/2;if(a(k).css("position")=="absolute"){a(k).css("margin-left",marginleft+marginl);a(k).css("margin-top",margintop+margint)}a(k).css("zoom","1");a(k).css("-ms-transform",mtrx)}}else if(a.browser.webkit){a(k).css("-webkit-transform",mtrx)}else if(a.browser.opera){a(k).css("-o-transform",mtrx)}else if(a.browser.mozilla){a(k).css("-moz-transform",mtrx)}else{a(k).css("transform",mtrx)}}},40)}else{l=j+g}return this})}})(jQuery);$.fn.rotate.defaults={speed:500,direction:"short",value:"relative",after:function(){}}

